[project]
name = "openrouter-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "requests>=2.34.2",
]

[project.scripts]
fetch = "openrouter_analysis.fetch:main"
sort = "openrouter_analysis.sort:main"
[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
